[theme]
primaryColor = "#A260D7"  # Light Purple (Button and Highlight Colors)
backgroundColor = "#C1F0FC"  # Light Blue (App Background)
secondaryBackgroundColor = "#FFFFFF"  # White for sidebar and widgets
textColor = "#54207E"  # Dark Purple (Main Text)
font = "sans serif"